### ISSUE TITLE
Q3 player brandon's hat does not render

### ISSUE THREAD

**Issue by zturtleman** [zturtleman/spearmint#175]
Both Spearmint and ioquake3 show a warning when loading the brandon player.

```
WARNING: R_FindImageFile could not find 'models/players/light/brandon/branhat.glow.tga' in shader 'models/players/brandon/branhat'
Shader models/players/brandon/branhat has a stage with no image
```

ioquake3 uses shader_t \* from R_FindShader internally (which does not get set to tr.defaultShader).

Spearmint uses qhandle_t from trap_R_RegisterShaderEx (which get set to 0 for defaultShader).

mint-arena makes shader handle 0 invisible to be compatible with Q3 not rendering missing shaders, when that is disabled it shows default image.

ioquake3 developer mode spams the following each frame;

```
WARNING: no shader for surface h_hat in skin models/players/brandon/head_default.skin
```

This is a data issue.
- Solution A) add image or change the shader.
- Solution B) ???

**Comment by coltongit** [comment]
Mapping a shader to that directory also fixes that issue & also allows the shader to work. I might wanna try that actually...
