### ISSUE TITLE
Allow servers to disable dropins

### ISSUE THREAD

**Issue by mecwerks** [zturtleman/spearmint#189]
It would be ideal to allow servers to disable in-game dropins/dropouts (mostly for mods that would want their servers to work this way). But before that it would be necessary to allow clients to add split-screen players from lobby/start server menu. Ties in with #18.

Is a lobby system something planned for Spearmint?

**Comment by zturtleman** [comment]
Fixed in devil branch for Spearmint 0.5. engine: https://github.com/zturtleman/spearmint/commit/e7d22e191fe8b4c598e6790ed37352fe2290394f, mod: https://github.com/zturtleman/mint-arena/commit/65e29df1921213f106dbfd6e1103e149843eddb8
