### ISSUE TITLE
Proper Open Arena support

### ISSUE THREAD

**Issue by Danfun64** [zturtleman/spearmint#194]
Open Arena runs fine with the q3a code, but it lacks many OA features. For example, OA has Team Arena features built-in. Then there is the matter of modes not even in Team Arena! I am sure this would be low priority, and #192 would need to be fixed first, but it would be nice to have, especially with Spearmint's split screen capabilities.

**Comment by zturtleman** [comment]
I have no plans to port this, closing issue.
