### ISSUE TITLE
Files not found when a mod is loaded.

### ISSUE THREAD

**Issue by mecwerks** [zturtleman/spearmint#207]
When in a mod changing map while in game causes a no default.cfg found error

```
execing default.cfg
execing config.cfg
execing config.cfg
couldn't exec autoexec.cfg
Failed to exec default.cfg
```

**Comment by mecwerks** [comment]
Hmmm, seems like when using a mod, and in a game, the directories added with addDir in the settings don't get searched. Supplying default.cfg just made it fail at finding the map.

**Comment by zturtleman** [comment]
mint-game.settings needs to be in a pk3 to be used on pure servers.

**Comment by mecwerks** [comment]
Okay thanks, that seems to have worked
