### ISSUE TITLE
Splitscreen viewport suggestion

### ISSUE THREAD

**Issue by mecwerks** [zturtleman/spearmint#210]
What about adding an option that allows bordered splitscreen viewports instead of stretching them to fill the screen? Or to allow it to just extend the fov? the stretching causes some stuff to look pretty weird :P

**Comment by zturtleman** [comment]
The FOV issue applies to any viewport that is very wide, not only splitscreen. I'd fix it if I knew how. :/

**Comment by mecwerks** [comment]
That sucks. It stinks to see stuff like this lol https://www.dropbox.com/s/1s17z76an12jjd7/Screenshot%20from%202015-05-26%2014%3A11%3A14.png?dl=0

**Comment by zturtleman** [comment]
It's not as bad when using cg_fov 90 (which when cg_fovAspectAdjust is enable is not _actually_ 90 degrees because it's altered to fit the viewport aspect). Turtle Arena even uses cg_fov 70 so that the stretching at edge of view is less noticeable. Though, this isn't really a fix for warped perspective.

**Comment by KuehnhammerTobias** [comment]
Isn't this more and more a problem of all those new aspect ratios > 16:9?
I saw some really ugly screenshots of panels bigger than that!
@mecwerks I assume you already know this, but only to get sure, possibly try horizontal splitscreen
setting. Some said even on 16:9 their gameplay experience was better (after some time to get used to)

**Comment by mecwerks** [comment]
@KuehnhammerTobias I don't usually play on splitscreen but thanks for the suggestion. I was just throwing out an idea because i noticed how it looked warped.

**Comment by KuehnhammerTobias** [comment]
BTW, after playing with the cvars zturtleman already mentioned you can get really good results (on < 16:9 at least):
Horizontal splitscreen, cg_fov 80, cg_fovAspectAdjust 0
![ssh](https://cloud.githubusercontent.com/assets/5429387/7822757/fdb194ca-03f7-11e5-9053-02826392e1f3.jpg)
Vertical splitscreen, cg_fov 80, cg_fovAspectAdjust 1
![ssv](https://cloud.githubusercontent.com/assets/5429387/7822791/324b7f5c-03f8-11e5-8e70-7d289af0ece2.jpg)
