### ISSUE TITLE
Request: 3 player splitscreen equal viewing size.

### ISSUE THREAD

**Issue by Danfun64** [zturtleman/spearmint#215]
Another wishlist item, but it would be nice if 3 player splitscreen was like 4 player splitscreen but has the score where p4 viewpoint would be, ala the dreamcast port:www.youtube.com/watch?v=Pt1J8k96IEY

**Comment by zturtleman** [comment]
Added a cvar for this behavior (enabled by default) in https://github.com/zturtleman/mint-arena/commit/881ccf2a915e1d2f6d29fb4e8d1b08887a9aeec1.

**Comment by Danfun64** [comment]
The scoreboard p4 feature is nice, but it only lists the top 5 players (I experimented with 3 split screen players and 5 bots). Maybe you can add a resize feature like how the regular score feature works?

**Comment by zturtleman** [comment]
Made it use smaller text when they do not all fit, allows up to 16 players now. https://github.com/zturtleman/mint-arena/commit/abeed4814c474e4532e8238c005ef4c4eb52e786
