### ISSUE TITLE
Make bot battle chase / retreat AI nodes handle blocked by mover

### ISSUE THREAD

**Issue by zturtleman** [zturtleman/spearmint#220]
(reported at https://www.youtube.com/watch?v=TJYbCjxSp2Q&lc=z12zyztpfxrrt1qde225txbaqyjrzn1qp04)

If bot on top of floor door in q3dm7 tries to attack a bot in the underground area, the bot does not try to open the door and instead keeps moving around on door shooting at enemy. Though battling through the vent doesn't seem to work well. `¯\_(ツ)_/¯`

Code-wise this seems like the intended behavior. The battle chase/retreat AI nodes call BotAIBlocked(activate=qfalse) intentionally not activating the door (although, I haven't check if qtrue will cause the bot to open the door or if bot switches back to battle mode). The correct behavior may be to not try to battle a enemy that is unreachable. Though, it seems like the bot should decide if the enemy should be pursued (thus opening the door) if enemy has CTF flag or if the bot is aggressive etc. Maybe battling through the vent is fine. I'm not really sure.

The issue probably exists in ioquake3 as well. I don't think it's a major issue, but might be nice to find a solution / keep in mind when improving the bot blocked AI.

**Comment by coltongit** [comment]
I can confirm this doesn't happen in ioquake3. I tried this with the latest ioquake3 git.

**Comment by coltongit** [comment]
Also, you might want to check if activate=qtrue fixes this particular issue.

**Comment by zturtleman** [comment]
activate=qtrue does not fix it. Bot switches back to battle AI if finds enemy.

**Comment by coltongit** [comment]
Then try making a subroutine that if the enemy is unreachable, and if so, then make it go activate the door, then fight the enemy.

**Comment by zturtleman** [comment]
When I tested ioquake3 by standing under the door with god mode enabled, the bot stayed there attacking for over 10 minutes before I quit. It ran out of ammo and was using gauntlet. -_-; The same also happened in Spearmint. So.. I don't think this is a Spearmint specific issue. It also seems unrelated to the to the [bot movement prediction issue](https://github.com/zturtleman/spearmint/commit/55a0a0ea99f1926a53d17a1240a625a66c187999).

Bots now activate entities in battle chase / retreat / nearby goal. When a bot goes and opens the trap door in q3dm7 and then pursues a no longer visible enemy &mdash; it's just really cool. https://github.com/zturtleman/mint-arena/compare/f10b0870f6df...116ec08b3843.

**Comment by coltongit** [comment]
THANK YOU ZACK!!!!! Q3DM7 is now officially FIXED!!!!

**Comment by coltongit** [comment]
And also, shouldn;t you report this to the ioquake 3 team Zack?
