### ISSUE TITLE
Linker file unused because linking not done for the Windows 32-bit version of Spearmint

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#222]
I don't know why, but the x86 version spits out "warning: linker file unused because linking not done" when compiling the x86 version of Spearmint. This doesn't happen with my 55a0a0e fork on my page. Can you please fix this? Thanks in advance.

**Comment by zturtleman** [comment]
Unable to reproduce issue using mingw-w64 on Debian 8 or cygwin/mingw-w64 on Windows 10.

**Comment by coltongit** [comment]
I have updated my Cygwin packages, but the issue is still there.
Here's what I get from Cygwin:
`Colton@ColtonsPC ~/spearmint
$ make ARCH=x86
make[1]: Entering directory '/home/Colton/spearmint'

Building in build/release-mingw32-x86:
  PLATFORM: mingw32
  ARCH: x86
  VERSION: 0.2_GIT_775ccff-2016-05-08
  COMPILE_PLATFORM: cygwin
  COMPILE_ARCH: x86_64
  CC: /usr/bin/i686-w64-mingw32-gcc /usr/bin/i686-pc-mingw32-gcc
  WINDRES: /usr/bin/i686-w64-mingw32-windres

  CFLAGS:
    -Wall -fno-strict-aliasing -Wimplicit -Wstrict-prototypes
    -DUSE_ICON -DWINVER=0x501 -m32 -DNO_GZIP -Icode/zlib
    -DUSE_INTERNAL_JPEG -Icode/jpeg-8c -DBUILD_FREETYPE
    -Icode/freetype-2.6/include -DFT2_BUILD_LIBRARY -DUSE_LOCAL_HEADERS
    -DPRODUCT_VERSION="0.2_GIT_775ccff-2016-05-08" -DBASEGAME="baseq3"
    -Wformat=2 -Wno-format-zero-length -Wformat-security -Wno-format-nonliteral
    -Wstrict-aliasing=2 -Wmissing-format-attribute -Wdisabled-optimization
    -Werror-implicit-function-declaration -MMD -DNDEBUG -O3 -march=i586
    -ffast-math

  CLIENT_CFLAGS:
    -DCURL_STATICLIB -Icode/SDL2/include -DUSE_OPENAL -DUSE_OPENAL_DLOPEN
    -DUSE_CURL -DUSE_VOIP -DUSE_CODEC_OPUS -DOPUS_BUILD -DHAVE_LRINTF
    -DFLOATING_POINT -DUSE_ALLOCA -Icode/opus-1.1/include -Icode/opus-1.1/celt
    -Icode/opus-1.1/silk -Icode/opus-1.1/silk/float -Icode/opusfile-0.5/include
    -DUSE_CODEC_VORBIS -Icode/libvorbis-1.3.4/include
    -Icode/libvorbis-1.3.4/lib -Icode/libogg-1.3.1/include
    -DUSE_RENDERER_DLOPEN -DUSE_MUMBLE

  SERVER_CFLAGS:
    -DUSE_VOIP

  LDFLAGS:


  LIBS:
    -lws2_32 -lwinmm -lpsapi

  CLIENT_LIBS:
    -lgdi32 -lole32 code/libs/win32/libcurl.a -lmingw32
    code/libs/win32/libSDL2main.a code/libs/win32/libSDL2.dll.a

  Output:
    spearmint-server_x86.exe
    spearmint_x86.exe
    mint-renderer-opengl1_x86.dll
    mint-renderer-opengl2_x86.dll
    SDL2.dll

make[2]: Entering directory '/home/Colton/spearmint'
DED_CC code/server/sv_bot.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/server/sv_client.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/server/sv_ccmds.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/server/sv_game.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/server/sv_init.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/server/sv_main.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/server/sv_net_chan.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/server/sv_snapshot.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/server/sv_world.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/bsp.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/bsp_q3.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/bsp_q3test106.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/bsp_fakk.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/bsp_sof2.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/bsp_ef2.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/bsp_mohaa.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/cm_load.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/cm_patch.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/cm_polylib.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/cm_test.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/cm_trace.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/cmd.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/common.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/cvar.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/files.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/md4.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/msg.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/net_chan.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/net_ip.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/huffman.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/q_math.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/q_shared.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/unzip.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/ioapi.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/vm.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/vm_interpreted.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_bspq3.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_cluster.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_debug.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_entity.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_file.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_main.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_move.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_optimize.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_reach.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_route.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_routealt.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_aas_sample.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/be_interface.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/l_crc.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/l_libvar.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/l_log.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/l_memory.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/l_precomp.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/l_script.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
BOT_CC code/botlib/l_struct.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/null/null_client.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/null/null_input.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/null/null_snddma.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/sys/con_log.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/sys/sys_main.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/server/sv_ref.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/renderergl1/tr_animation_mds.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/renderergl1/tr_animation_mdm.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/renderergl1/tr_model.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/renderergl1/tr_model_iqm.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
AS code/asm/matha.s
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
CC code/asm/snapvector.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
CC code/asm/ftola.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/zlib/adler32.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/zlib/crc32.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/zlib/inffast.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/zlib/inflate.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/zlib/inftrees.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/zlib/zutil.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/qcommon/vm_x86.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
WINDRES code/sys/win_resource.rc
DED_CC code/sys/sys_win32.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
DED_CC code/sys/con_win32.c
i686-w64-mingw32-gcc: warning: /usr/bin/i686-pc-mingw32-gcc: linker input file unused because linking not done
LD build/release-mingw32-x86/spearmint-server_x86.exe
/usr/bin/i686-pc-mingw32-gcc: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:2001: recipe for target 'build/release-mingw32-x86/spearmint-server_x86.exe' failed
make[2]: *** [build/release-mingw32-x86/spearmint-server_x86.exe] Error 1
make[2]: Leaving directory '/home/Colton/spearmint'
Makefile:1193: recipe for target 'targets' failed
make[1]: *** [targets] Error 2
make[1]: Leaving directory '/home/Colton/spearmint'
Makefile:1144: recipe for target 'release' failed
make: *** [release] Error 2
`

**Comment by mecwerks** [comment]
I believe you're building it wrong. Try running "make COMPILE_ARCH=x86" instead

**Comment by coltongit** [comment]
OK. I was using ARCH=x86 instead, & it worked just fine until 55a0a0e.

**Comment by zturtleman** [comment]
`make ARCH=x86` is correct. It thinks the compiler is "/usr/bin/i686-w64-mingw32-gcc /usr/bin/i686-pc-mingw32-gcc". There should only be _one_ gcc. The other compiler is passed as an argument. Apparently, Makefile did not expect multiple mingw toolchains to be installed. I think this is fixed in [master now](https://github.com/zturtleman/spearmint/commit/01cc677cd37b350f769e6bacc8e1f1183f21250d).
