### ISSUE TITLE
Issue with the latest spearmint

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#224]
It seems that Spearmint bugged out on me :( I ended up losing my save data because of this... It doesn't want to write config.cfg or consolehistory.dat for some reason. And I had to pull all the maps I downloaded from the baseq3 folder because of this...

**Comment by zturtleman** [comment]
Does running `print fs_homepath` console command show the location you are expecting files? Does your operating system user account have permission to write to the directory?

How many pk3 files are there? Did removing them fix config not being saved? I think the engine keeps all of the pk3 files open. Maybe it ran out of file handles. I think the limit is 512 file handles in ioq3/Spearmint on Windows.

**Comment by coltongit** [comment]
I haven't tried that yet... I'll try when I get home...

**Comment by coltongit** [comment]
I've changed the permissions... Nada. Tried changing the homepath... But I can't load my custom maps. Meaning it could actually be a bug with the latest source code for Spearmint.

**Comment by zturtleman** [comment]
I don't remember changing anything that would break file writing and it works for me (on Debian at least). I have no idea how I can do anything about it.

Does it work if you build the release-0.2 tag? (`git checkout release-0.2; make clean release BUILD_SERVER=0 -j2`)

**Comment by coltongit** [comment]
Yes. It also works with the 55a0a0e fork I made of this a while back
on my page. It doesn't have the q3dm7 bot fix though. I made a pk3 of
the latest patch data, though.

**Comment by mecwerks** [comment]
I've run spearmint latest commit on my Ubuntu server machine and could not reproduce the issue.

**Comment by KuehnhammerTobias** [comment]
Ditto, not reproducible for me, on Win 8.1 and Win 7.

**Comment by coltongit** [comment]
Maybe the issue is I have to run it as admin.

**Comment by mecwerks** [comment]
If you have to run it as admin then I'd say you don't have proper permissions set on your directories.

**Comment by coltongit** [comment]
I have the proper permissions set on it already, but I don't know why
it did this... I switched back to my 55a0a0e fork for now because of
this. Works fine and dandy with the latest mint-arena compile.
