### ISSUE TITLE
Mind adding the spmap cvar from the original Q3?

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#225]
I miss the spmap cvar. You could test how a map is going to play in single player with this cvar. It essentially loads a map in single player mode. Mind adding it back into Spearmint? I would love to be able to use it again.

**Comment by ensiform** [comment]
```g_gametype <whatever gametype>; devmap <mapname>```

**Comment by coltongit** [comment]
I prefer having just ONE cvar that will do all that for me. Even if I end
up having to reimplement it myself.

**Comment by ensiform** [comment]
Lazy.

**Comment by coltongit** [comment]
It's the way it was in the original Q3, as well as in ioquake3, so I know
that cvar was in there originally.

**Comment by ensiform** [comment]
sp(dev)map isn't a cvar, its a command that has special properties though I'm not even sure it was actually used by the menu was it?

**Comment by coltongit** [comment]
It can be activated by a cvar in the original Q3A/ioq3 with /spmap
(mapname) or /spdevmap (mapname).

**Comment by ensiform** [comment]
A cvar is a console variable, spmap and spdevmap are not cvars, they are console commands FYI.


I still don't see why it's necessary to have.  Considering its an engine command and specific to q3, does it belong in an engine that isn't game specific?

**Comment by coltongit** [comment]
They can be converted into cars for exclusive use with Spearmint Q3A only.

**Comment by zturtleman** [comment]
ui_singlePlayerActive (read only) needs to be enabled like Team Arena. Added spmap and spdevmap commands to q3_ui. https://github.com/zturtleman/mint-arena/commit/7945d53573a4f9426a52d8c0af414bc7befa8732
