### ISSUE TITLE
BIG Info string length exceeded when loading any map

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#226]
I happen to have come across a bug in Spearmint. What happens is when you load a map, & afterwards pull down the console, you will see "BIG Info string length exceeded" three times in a row on the screen. This also happens, albeit only once, when reloading a map that's already loaded (such as when completing a match). Mind looking into this Zack? Would be appreciated.

**Comment by zturtleman** [comment]
I'm unable to the reproduce issue. I think the only big info string is CS_SYSTEMINFO. Run `configstrings` and check index 1 on the list.

**Comment by coltongit** [comment]
The reason this happens seems to be due to my custom maps in the baseq3 directory. They were downloaded from lvlworld, ws.q3df, & other various map sites. Yeah, I know, I'm a custom map fan XD

**Comment by mecwerks** [comment]
please keep in mind when checking for bugs to make sure it is actually a spearmint bug before posting the issue. The best way to do this is to have a separate clean install of spearmint without any modifications to it, maps, models, tweaked configs, etc.

**Comment by coltongit** [comment]
Acknowledged.
