### ISSUE TITLE
Make bots avoid solid areas on the floor

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#230]
Shouldn't the bots be able to detect solid areas on the map and jump over them? I think so. I wonder if any of the other contributors think the same way. At the very least, it'll make botplay much better for some maps by jumping over their solid areas, for example 17t6remix/17t6ctf.

**Comment by zturtleman** [comment]
It's not that kind of solid area. It would be better called _the inaccessible void that has no way to plot a path anywhere_. AAS area 0 is "solid area", there is not multiple "solid areas".

I think the solution would be changing BSPC to correctly create an AAS area there, not make the run-time bot AI handle avoiding "the inaccessible void" that it managed to come in contact with. Or changing the BSP used to create the AAS (which doesn't have to be the BSP you use in game) as suggested in the [other issue](https://github.com/zturtleman/spearmint/issues/223) &mdash; which I would guess is the easiest/fastest option.

I'm not going to work on this in the foreseeable future. There is a lot of things I'd rather do than fix bots on two user made maps that shipped with broken bot support. If someone else wants to step up and do this on their own (for example, @coltongit), yeah that's fine. I don't have any pointers of where to start.
