### ISSUE TITLE
Open Arena svn has the files you patched out with dummy files

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#231]
I happened to notice that the Open Arena svn has the files that were patched out in Spearmint with dummy files.
Here's the link to the SVN containing the files:
http://openarena.ws/svn.html
Go to models/players/beret/ & you'll see them as jpg files. Also, the SVN player_beret.shader must be used as well. Should be in scripts/ in the SVN.

**Comment by zturtleman** [comment]
The patch data is for OpenArena 0.8.8. spearmint-patch-data does not intend to introduce new data files. The dummy files are requires to match Quake 3 engine behavior for skin rendering. Without the dummy files the shaders with missing images are not rendered.
