### ISSUE TITLE
The bots only grab the 5 health in q3dm7 if they take too long to activate the door

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#233]
When I say that, I actually mean this:
![shot0000](https://cloud.githubusercontent.com/assets/17090935/15231455/a9798b8a-1871-11e6-85e8-b822f7ce93d6.png)
Shouldn't they grab the 5 health before they go to activate the door? That's just my absolute thinking. Because I really do like how they go up towards the button, activate the door, then go into the room below the door, & come out near the RL. That was pure awesomeness right there. As mentioned earlier, they don't grab the 5 health near the door, they only grab it if they take too long to activate it in the first place, so that's why I think they should grab the 5 health before going up to activate the door.

**Comment by ensiform** [comment]
Why are you so concerned with bot behavior that probably exists in q3 as well?

I don't think it's necessarily in the perview of the project to necessarily change bot routes on maps that exist stock or custom.

**Comment by coltongit** [comment]
It's only my opinion, Ensiform. I doesn't have to be a real issue, in fact,
the next time I'm on github, I'll go ahead & close this.
