### ISSUE TITLE
Turn on autochat when the engine loads

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#234]
Shouldn't it be possible to turn on autochat (the legacy Quake 3 chat behavior for the console chat) as soon as the engine loads? It would make it so that way you don't have to type in "set con_autochat 1" when you start the engine for the first time. The intended autochat behavior occurs with legacy Q3A as well as ioq3.

**Comment by zturtleman** [comment]
It is intentionally disabled in Spearmint, with a cvar for those who desire the behavior. This is the intended behavior in Spearmint.
