### ISSUE TITLE
Is it possible to include legacy mod/demo support into Spearmint?

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#235]
I know that Spearmint doesn't support legacy mods/demos, but can it be possible to do such with the engine? That may mean that the legacy API for the cgame/qagame vms/dlls would have to be taken care of first. Meaning this could be 0.4 material.

**Comment by zturtleman** [comment]
I keep moving code from the engine into the Game and CGame VMs or changing how features are handled, so the engine is actually missing a lot of stuff that Q3 VMs need at this point.

I've thought about it the possibility of having the Spearmint VMs load Q3 VMs (#180, currently not possible), so they can provide the missing functionality / converts network data and system calls to Q3 VM APIs. But.. I don't really see the benefit.

The primary goal of Spearmint is more or less doing cool stuff that breaks Q3 network or mod compatibility, or that generally I don't think it appropriate for "vanilla quake3" compatible engines such as ioquake3. Spearmint was co-developed / a fork of the engine used by Turtle Arena with the intention of providing an improved ioquake3 for creating _new standalone games_. The game portion of Turtle Arena wasn't really convincing that the engine is actually useful. An issue I ran into with many game engines was that there wasn't a complete game to start a project off, so keeping Quake 3 playable (and improving it) was always a goal for "ioq3ztm". ioq3ztm originated from conditional "#ifdef IOQ3ZTM" code in Turtle Arena (which to this day still has a ton IOQ3ZTM code that I haven't ported to mint-arena yet).

It's kind of "ZTM's Q3 mod that he hasn't really named and requires it's own engine" (though, advertising the engine for playing Quake 3 was never the original intention). My efforts to make the engine more flexible, assimilate features from other Free Software Quake 3 based games, and able to handle features required by other proprietary games were backed by the reasoning of expanding options available to _new standalone games_ and my own knowledge of decisions that other developers made when working with the Quake 3 engine.

Running Q3 VMs doesn't help doesn't seem like it works toward any of my goals. It just leaves us rolling in the mud of legacy limitations.
