### ISSUE TITLE
Isn't Spearmint 0.3 releasing today?

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#236]
Shouldn't the Spearmint 0.3 release be uploaded to the spearmint homepage? Well, it IS the release date for 0.3 (May 13, 2016). I'm pretty sure we have come a long way since 0.2, for example, we fixed the botplay bug for q3dm7, we fixed the lightning bolt shader bug for the patch data, & many, many more fixes have been done!

**Comment by aisouard** [comment]
It should be available over here : https://github.com/zturtleman/spearmint/tree/release-0.3

**Comment by zturtleman** [comment]
It took a few hours longer than I'd planned. Spearmint 0.3 released [blog post](http://clover.moe/2016/05/13/spearmint-0-3-released/) &bull; [download](http://spearmint.pw)

**Comment by coltongit** [comment]
It still shows 2015 as the release year @zturtleman.

**Comment by coltongit** [comment]
Thanks.

**Comment by zturtleman** [comment]
:laughing: Thanks for pointing the year out. I'm fixing the readme files in the downloads right now.

**Comment by coltongit** [comment]
I saw your fixes to the readme. Thanks again.
