### ISSUE TITLE
Feature request: Be able to change the color of the font of the HUD in the Q3 Demo Test

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#238]
I happen to have a feature request @zturtleman, it happens to be if it can be possible to make a menu option to change the color of the font in the HUD in the Q3A Demo Test. It is currently yellow in Spearmint. You could set it in either system or player settings (I think this feature would work perfectly in there), and even be able to select a custom hex value for the color. Thanks in advance.

**Comment by zturtleman** [comment]
if you want to change the status bar number colors, do it [here](https://github.com/zturtleman/mint-arena/blob/0c30a06/code/cgame/cg_draw.c#L381) (the old colors are even still present and comments still call normal health color green lol). I'm not going to add a menu option for it.
