### ISSUE TITLE
Another feature request: Be able to save/load your own control configs like in the Q3A Demo Test

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#239]
The Q3A demo test had a full menu option where you could name and save your control configs, so that way you could execute them at run time on someone else's installation using a batch file/shortcut (if you brought the config with you, that is). Here's a few snapshots of this:
![q3 demo test config load or save option](https://cloud.githubusercontent.com/assets/17090935/15260579/f621f712-192d-11e6-8f67-ce549b9e2381.png)
The main setup menu. Notice the save/load options. These are for saving/loading your own control configs, for use anywhere on the go (if you wanted to do that & take your controls with you).
![quake 3 1 09 feature request to zturtleman](https://cloud.githubusercontent.com/assets/17090935/15260655/6e070ee8-192e-11e6-96a9-003ebeb4116b.JPG)
Same thing, but with console dropped down.
![q3 demo test load config menu](https://cloud.githubusercontent.com/assets/17090935/15260604/1950e856-192e-11e6-9452-fdc2a01db7e1.png)
This is where you would load your control configs. One you load a config, the controls stored will automatically be binded in the controls menu.
![q3 demo test save config menu](https://cloud.githubusercontent.com/assets/17090935/15260629/42c947e6-192e-11e6-8d89-7707eed6bed5.png)
This is where you would save your control configs. Once you save a config, it will take the current control bindings & write them to a .cfg file with whatever name you choose.

**Comment by zturtleman** [comment]
The menus are wrappers for these three console commands.
```
writeconfig colton.cfg
dir "" cfg
exec colton.cfg
```
The code for the menus is still present but disabled in Q3 GPL release, ioquake3, and mint-arena. I don't plan to re-enable it.
