### ISSUE TITLE
Stop Q3A from loading sound/player/announce/<playername>.wav

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#240]
This issue also seems to happen on the legacy Q3A, as well as ioq3. What happens is that the game tries to load sound/player/announce/%playername%.wav, but it shouldn't load it. It could be useful for a custom announcer sound though...

**Comment by KuehnhammerTobias** [comment]
WHAT:question:
Why are announcer sounds an issue?
:open_mouth:

**Comment by coltongit** [comment]
I think that for some, the player announcer sound could be an issue with gameplay.
For others, however, it could be cool to have your own announcer sound play in the SP campaign. SO yes, I understand your point, @KuehnhammerTobias.

**Comment by coltongit** [comment]
Since this is an issue based on preference & not really a game issue, I am now closing this issue. Closed.
