### ISSUE TITLE
Quake 3 Demo Test used different text for the main menu

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#241]
It actually used different text for the bottom of the main menu than the demo.
Spearmint uses the plain demo's text, seen here:
![shot0002](https://cloud.githubusercontent.com/assets/17090935/15270958/eb1c427e-1a08-11e6-991f-bdf59c897d9b.png)
The real demo test has this text instead:
![q3 demo test main menu](https://cloud.githubusercontent.com/assets/17090935/15270974/643a944e-1a09-11e6-9d68-a70be6f0bbe1.png)
I don't mean to keep pestering you with stuff like this, but in this special case I'm going to assume a cvar of `set ui_demoq3test 1` will probably fix this (and the mint-game.settings will have to be modified to permanently activate this behavior). Of course the trademark section will stay the same as what Spearmint uses already for the demo, however. You're getting it down, @zturtleman. Once this is done, we won't have to do any more with the demo test/demo.

**Comment by zturtleman** [comment]
Let's not. Demo test needs code changes for hud status bar number colors, disabling/changing assets, and adding save/load config menus and most likely other things to replicate the original behavior. The demoq3 code was already in the code base for whatever reason, so allowing it to actually be used made sense. (Set developer 1 and hit F12 to screenshot menu in Spearmint Q3.)
