### ISSUE TITLE
Add text to readme.md concerning unofficial patch data

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#242]
I would like to see a section of the readme.md denoting that unofficial patch data can be used, but at the risk of the user, the fact that this unofficial patch data's functionality can disintegrate as time goes on, & the true fact that you, @zturtleman, do not support these unofficial patch data sources. My unofficial patch data repo has been edited to account for this.

**Comment by zturtleman** [comment]
As I stated on [#232](https://github.com/zturtleman/spearmint/issues/232#issuecomment-219042747), I'm not going to link to mods that are copyright infringement (data copied out of Q3 pk3s).

**Comment by coltongit** [comment]
You don't have to link to them, I'm simply stating that unofficial patches
can be used, but only at the risk of the user.
