### ISSUE TITLE
Bots in demoq3/demoq3test use gauntlet instead of machinegun as first weapon and try to fire weapons with no ammo in them

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#244]
I just tested demoq3  and demoq3test and the bots keep getting distracted when trying to activate the q3dm7 door. Also, the bots prefer the gauntlet rather than the machinegun as the first weapon they spawn with, & they try to fire weapons with no ammo in them.

**Comment by zturtleman** [comment]
Is the botfiles/inv.h from spearmint-patch-data being used? `which botfiles/inv.h` in Spearmint console will give path it's accessed from.

**Comment by coltongit** [comment]
Yes, it is being used @zturtleman.

**Comment by zturtleman** [comment]
Okay. I don't know off hand what the issue is.

**Comment by coltongit** [comment]
Me neither, but I'm thinking it's probably due to me using a different copy
of spearmint and using a fs_cdpath command to switch to that copy, along
with an fs_homepath as well.

**Comment by coltongit** [comment]
I'll add the inv.h's to the other spearmint folder I'm using. That oughta solve the issue.

**Comment by zturtleman** [comment]
Well using the inv.h from spearmint-patch-data, when I disable all the pick up weapons on q3dm1 Sarge never uses Gauntlet until out of ammo and switches back to machine gun after picking up bullets. Note: each bot has their own weapon selection preferences. `set disable_weapon_shotgun 1; set disable_weapon_rocketlauncher 1; set disable_weapon_plasmagun 1`

When I use inv.h from demoq3/pak0.pk3 it always uses Gauntlet. So it seems like your not using the new inv.h...

If `which botfiles/inv.h` says it's in demoq3/pak0.pk3 you're using the wrong one (run it after loading the map to be sure). Also, make sure you either put it in a pk3 or set sv_pure 0.

**Comment by coltongit** [comment]
It's using the one in spearmint's game directory and still having the problem.

**Comment by coltongit** [comment]
Zipping up the inv.h into a pk3 works fine now, this issue and the bots stuck in RA room issue has been fixed for me. Both will now be closed.
