### ISSUE TITLE
Maybe make icons for demoq3test in spearmint-patch-data

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#245]
Shouldn't it be possible to make icons for demoq3test in spearmint-patch-data? Someone should make those, but not me, because I'm not a good icon editor anyway.

**Comment by KuehnhammerTobias** [comment]
Someone should integrate all those next-gen-features as seen in Crysis 2 etc., but not me, because I'm not a good code editor anyway. :smirk:

**Comment by ensiform** [comment]
I'm not ztm but I would imagine continuing to support this unreleased version of q3 in this fork.

**Comment by coltongit** [comment]
id released it because they publicly bug tested the game by making a 
test release available at specific points in 1999. This demo test was 
the last of these test releases @Ensiform.

**Comment by ensiform** [comment]
Correct but it's not an official version.  Nor is it intended to be compatible with 1.32c/GPL codebase

**Comment by zturtleman** [comment]
<img src="https://raw.githubusercontent.com/zturtleman/spearmint-patch-data/master/demoq3test/windowicon.png" align="right" height="192" width="192" alt="demoq3test icon" > I added an icon for demo Q3 test in https://github.com/zturtleman/spearmint-patch-data/commit/6231ea6a36d39ec9a7e9fb85cfe7072334283781.
