### ISSUE TITLE
Q3Test 1.08 is the first Q3Test version to introduce Sarge

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#249]
I think you might want to know that Sarge made his first official debut in Q3Test 1.08. Your 1.08 mint-game.settings says Visor is the only one there. In 1.03-1.07, this is true, but you can access Sarge in 1.08 by typing in model sarge in the 1.08 console, & it will allow you to use Sarge as your player model. Then again, this isn't _really_ an issue, just that it's user preference.

**Comment by zturtleman** [comment]
https://github.com/zturtleman/spearmint-patch-data/commit/975ea57535440c6ac79114fd4a5f7ec6241cde10

**Comment by coltongit** [comment]
Thank you. Sarge probably would've gotten angry at you for not realizing his existence.
