### ISSUE TITLE
Is it possible to just let all players use whichever model they want/whatever custom skin they want for the 2 models that exist on Q3Test 1.08?

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#250]
I really don't think you really need the default model stuff in the Q3Test 1.08 mint-game.settings, because what if P1 wants to use Sarge instead of Visor (I know I do), or if P2 wants Visor instead of Sarge, etc. Here's the DL link to the new Q3Test 1.08 mint-game.settings with the Visor/Sarge restrictions removed: https://mega.nz/#!g191AQQA!Ew_HzUGqFnK2snp-DRhU-FTQ1_RYrBY9HihMVACUVl4
This is also true for all the custom skins created for Q3Test over the years (mainly for Visor, but there probably were some for Sarge as well). So it's not really feasible to include the player model restrictions for _any_ of the test releases at all.
DL link for the Q3Test 1.06 Visor restriction removed mint-game.settings:
https://mega.nz/#!B89CCTpa!XgOFsfu72C0Avyu6S6kULlQ7SugU4xMcFWoYaUo_oZc
Also, it turns out that there IS a full version of Q3Test 1.07. Here it is:
https://mega.nz/#!1kEmFR5Z!rfIvenHDLxu8Ms1j9WaN_zWJ7iXYsQRrh6e71U9Fb8c

**Comment by coltongit** [comment]
I guess this has to be left to the person/people wanting to use different skins, then.

**Comment by zturtleman** [comment]
`cvarDefault` doesn't restrict anything. You can change the cvars in-game to use any player you want to use.

`cvarDefault model` requires Spearmint git master, Spearmint 0.3 will error when CGame registers model command.
