### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by LavenderMoon** [zturtleman/spearmint#251]
Are you allowed to have Spearmint and Mint-Arena licensed under the GPLv3? I can't find anything that says id released Quake 3 under the GPLv2+ or GPLv3. I just recently found out that the GPLv2 and GPLv3 are incompatible with each other, so if id Software or Zenimax has given permission to use their GPLv2-licensed sources under the GPLv3, that would be very useful to know.

**Comment by ensiform** [comment]
Quake 3 is v2+

**Comment by ensiform** [comment]
Says so everywhere in the headers on the q3 and ioquake3 repos.

**Comment by LavenderMoon** [comment]
Ah, I'm an idiot.
