### ISSUE TITLE
The infinite flight glitch in Spearmint 0.3

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#253]
To reproduce:
1. Devmap into any map.
2. Spam give flight.
3. You will now have flight for the rest of the match (meaning infinite flight).
Also, I have also notified A+Start about this glitch. Unsure if he'll actually take it into consideration.
Also, the flight sound and movement remain, but the HUD for flight disappears.

**Comment by KuehnhammerTobias** [comment]
Hmm, I can't reproduce this issue.
Here is what happens to me:
I do step 1 - 3 you explained above. I will have the flight powerup for 60 seconds, after this time the powerup effect disappears (flying around is no longer possible), and the sound vanishes.
That's how it should work I assume.

Do you have some more information about this issue? For example, do you compile Spearmint and mint-arena by your own, or did you use the provided realease builds?
Is everything set to infinite, the movement, the sound, HUD, or is just one effect infinite?

**Comment by coltongit** [comment]
I used 0.3 (the main release build). The flight stuff disappears, but
the player still has the effects of flight wherever he moves for the
duration of the match.

**Comment by KuehnhammerTobias** [comment]
Eh, please don't edit your earlier comment for answering questions on later replies!
Anyways, sorry can't reproduce the issue, even if I use the release build too!

**Comment by zturtleman** [comment]
After running `give Flight` 17 times ("spam" meaning repetitively) the power up time left exceeds 999 seconds so CGame assumes it's a unlimited time power up (like a CTF Flag) and [doesn't draw the icon](https://github.com/zturtleman/mint-arena/blob/0c30a06/code/cgame/cg_draw.c#L1106). Setting timescale to 100 will eventually cause the icon to reappear and the power up to be removed after the time has elapsed (all functioning as normal). This also happens in ioquake3 and presumably vanilla Quake 3 since it's CGame has the same check.

**Comment by KuehnhammerTobias** [comment]
17 times (?) OMG. Who will do this? Well, didn't test this 17 times, sorry!

**Comment by ensiform** [comment]
It happens with all powerups and is not exclusive to spearmint.  In Q3A its 99 seconds in Q3TA its 999 I believe?

**Comment by zturtleman** [comment]
@ensiform Icon is shown up to 999 seconds in both Q3A and Q3TA, but Q3A limits count down display value to 99.

Fixed power up icon not being drawn when there is more than 999 seconds left in https://github.com/zturtleman/mint-arena/commit/a6e150043c609f1f0e0bf246f0d991d66ffa94a6.

**Comment by coltongit** [comment]
That means the infinite flight glitch has been patched already.

**Comment by coltongit** [comment]
Mind also having Q3A draw up to the same time limit as in Q3TA @zturtleman?

**Comment by zturtleman** [comment]
There was no infinite flight glitch, just the power up icon / counter not drawing when it lasts more than 999 seconds.

No, Q3A can keep it's max 99 display.

It's kind of a compatibility issue to change it in ioquake3. A server only mod could depend on the behavior. And it's not really an issue that would likely occur in regular use.

**Comment by coltongit** [comment]
It's technically the infinite flight glitch, @zturtleman. That's why I said that.

**Comment by mecwerks** [comment]
@coltongit I've messed with this before myself, there is no infinite flight glitch. After it gets to a certain amount of time left the display counter just doesn't show anymore. If you left it sitting there long enough for the timer to go back down it would start displaying again.
