### ISSUE TITLE
Enemy model for who last shot you isn't in the right place for players 3 & 4

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#255]
It seems (to me at least) that the enemy model for who last shot you for players 3 & 4 isn't in the correct window, it's between 2 windows.
Here's a snapshot of what I mean:
![shot0001](https://cloud.githubusercontent.com/assets/17090935/15548267/fded715c-227d-11e6-9908-0a9cdee98dfa.png)

**Comment by zturtleman** [comment]
Fixed in https://github.com/zturtleman/mint-arena/commit/914aff4e0a432dcf3850775ff5a3b1da8f4bbb23.
