### ISSUE TITLE
Make give all command also give grappling hook

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#256]
I think this one's been bugging me a little, but I think the "give all" command should also give you the grappling hook as well, as it's one of the factory Q3 weapons (albeit unused normally).

**Comment by mecwerks** [comment]
It's never used in any of the stock quake 3 maps. Just because you don't like it doesn't mean it should be put upstream into spearmint. Changes such as these should be put in your own private fork of spearmint.

**Comment by coltongit** [comment]
I would love to see it happen though. It really doesn't make any sense though to not include it in the list of all weapons accessible through give all anyway.

**Comment by zturtleman** [comment]
No reason to change this. I think from the point of view of `give all` being a developer command, giving a weapon that is not used in the game does not make sense. You get it using `give Grappling Hook` anyway.

**Comment by coltongit** [comment]
I could be possible to add an option to make it do that in the options menu however. There are custom maps which utilize the grappling hook, like for example mfspacedm2, referenced during our conversation in the comments of the "Bot, Follow Me" video of yours, @zturtleman.

**Comment by zturtleman** [comment]
No. Just use `give Grappling Hook`.
