### ISSUE TITLE
Make it possible to make Spearmint installers using modified ioquake3 nsi referenced in the compile script during make clean

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#258]
Shouldn't Spearmint installers be possible by using a modified version of the ioquake3 nsi script referenced during make clean? And shouldn't that ioquake3 leftover be fixed as well?

**Comment by zturtleman** [comment]
Fixed building in c0051e6557f61f175411394bd3907e4c16a4ddb6, renamed files in a2910451120f96f82b72d0f8566bef061ad78fca.

**Comment by coltongit** [comment]
I was going to say, shouldn't `make install` call the Nullsoft Install System to compile the nsi script for either a 32-bit or 64-bit installer & drop it in the corresponding build directory for that particular platform, @zturtleman? Also, it should have build switches for whether it should use the classic style or the modern style for the UI. And could you allow the installer to copy in the patch pk3s for Q3A in ioquake3 (& have a selection of games to install along with Spearmint)? (Q3A in both engines can only be installed if that particular person accepts the original Q3 EULA), & also have it copy the pak0.pk3 when the Q3A CD is in the drive?

**Comment by zturtleman** [comment]
`make install` is suppose to set up the software in your system directories to be able to run the software. Though, you can run ioq3 and Spearmint out of build directory without any problems (unlike many other Unix programs which require `make install`). Having `make install` create an installer doesn't make sense to me.

> classic style or the modern style for the UI

Installer UI? Game UI? I don't know what you're referring to.

Patch pk3s are installed by spearmint-q3a.nsi, which can also install pak0.pk3 from a CD. It does lack spearmint-patch-data however.

I originally made the Spearmint changes to the NSIS installer in 2012. I don't plan to release it.

**Comment by coltongit** [comment]
I mean the Installer UI @zturtleman. In the zip packager built into NSIS, there is an option to use a more minimalist (classic) UI or a fully graphical modern UI like what today's installers use.
