### ISSUE TITLE
Is it possible to add support for Spearmint to use mp2 files for player sounds (like in Q3 Revolution) as well as .zym models from Nexuiz (mainly because I would love to see them in Spearmint)

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#261]
Is it possible to add support for mp2 files for player audio as well as .zym models from Nexuiz as playable characters in Spearmint? And is it just me, or is it that I'd love to see some of the Nexuiz folks in the Arena Eternal? The reason for this is what if you wanted to use the player sounds for Q3R exclusive models like Reaper for example without having to convert them to WAV, which would waste quite a bit of time on the player's end, & would waste valuable time on the battlefields of the Arena Eternal.

**Comment by zturtleman** [comment]
Adding new sound codecs is possible. I don't know the specifics about zym format to be able to say. I have absolutely no interest in them myself. It would waste valuable time on the battlefields of the Programming Eternal.

**Comment by mecwerks** [comment]
Please ask yourself "why" this would be good to do in spearmint. Supporting older sound formats seems like going backwards. (especially when you could just re-encode them). As for the models, I don't think supporting models from a mod is exactly high on the priority list. If you'd like to see this happen you should look into it yourself.
