### ISSUE TITLE
Not really a Spearmint issue, but shouldn't forum.clover.moe include SSL support (https://)?

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#265]
Here's a feature request for forum.clover.moe @zturtleman.
Shouldn't forum.clover.moe include HTTPS support like github does?
Just a question.

**Comment by Mateos81** [comment]
May I ask why you haven't asked this on these forums, instead of creating an issue on Spearmint GH? ^^'

**Comment by coltongit** [comment]
Mainly because I'm at school & the school's main blocker doesn't support HTTPS. That why I would like clover.moe to use HTTPS, & it's also safer because data is encrypted on both ends, as well as in transit between the clover.moe server & the client browser accessing it.

**Comment by zturtleman** [comment]
The forum already supports HTTPS. I added it when I moved Discourse from chat.c.m to forum.c.m. https://forum.clover.moe.

**Comment by coltongit** [comment]
You might wanna make it default then, @zturtleman. Although this may break compatibility with legacy web browsers.

**Comment by zturtleman** [comment]
When I load http://forum.clover.moe in Google Chrome it redirects to https. I don't know the details, it's part of Discourse when I enable SSL. The links to forum.clover.moe that I've added to [clover.moe](http://clover.moe) and [Spearmint wiki](https://github.com/zturtleman/spearmint/wiki) use https. So it's already as close to default as I am aware it can be.
