### ISSUE TITLE
Not sure if these are issues, but I found these disturbing (to me at least)...

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#273]
Whenever you hit a teammate, there is no sound played. It should play "hit_teammate.wav" in pak0.pk3 whenever you hit one. Also, excellent_a.wav & impressive_a.wav should also be played if it isn't you who got either of those awards (if it was one of the enemies in FFA or anyone except you in CTF). This will also be reported to the ioq3 developers as well.

**Comment by KuehnhammerTobias** [comment]
hit_teammate.wav Is played for me (= cgs.media.hitTeamSound from 'CG_CheckLocalSounds')
excellent_a, impressive_a etc. are the audio files for the award menu, I don't hink they are scheduled to be played for enemies! The awards represent YOUR rewards, not the ones from your enemy!

**Comment by coltongit** [comment]
Oh. It doesn't play for me though. Is it possible the latest Spearmint compile fixes that?

**Comment by KuehnhammerTobias** [comment]
Eventually you have g_friendlyfire 0?

**Comment by coltongit** [comment]
Yes, I do, but shouldn't it play regardless of that integer value?

**Comment by KuehnhammerTobias** [comment]
In order to achieve what?

**Comment by coltongit** [comment]
I think it should be played regardless of that value so that way you can try to avoid killing teammates, as that hit sound could be used as a training tool, so that way the new player could figure out to not fire a teammate when friendly fire is turned on.

**Comment by KuehnhammerTobias** [comment]
I don't know, others might argue that the opposite is true. It's good to know when friendly fire is on (the Sound is played) or off ( no sound).
I think this is personal preference. For, example I personally don't like the whole hitsounds. They are 'misused' by humans compared to bots. For example, you (assuming you are human) will hear how many armor your enemy has. You can also fire some grenades round a Corner and 'hear' if your enemy is hit or not. Both things aren't considered by bots! To me this is not really plausible. though, most players don't care much about bots, so this is also a personal preference ...

**Comment by coltongit** [comment]
So essentially this could be a new option in the game options menu... Name candidate: "Always use hit teammate sound".

**Comment by KuehnhammerTobias** [comment]
Until your options menu will explode!
I'm not against it, but always consider if it is worth to add a cvar for your own preference! Eventually this is something for your own mod!

**Comment by coltongit** [comment]
I'll try to implement it for Spearmint baseq3... Maybe I'll also implement an option for the Q3TA hit behavior (high/medium/low hit sound depending on armor). The latter will be grayed out if missionpack's not installed, or if the Spearmint missionpack VM couldn't load due to some error. The prepare your team sound could be used in the same manner as the Q3TA hit behavior.

**Comment by KuehnhammerTobias** [comment]
BTW: What I've learned from zturtleman, if you talk about mint-arena (and games) use the term mint-arena. If you talk about the engine, use the term Spearmint!

All you have to do is rework code in mint-arena, the engine is not affected!
It's in 'CG_CheckLocalSounds' in cg_playerstate.c. The 'grayed out' thing has nothing to do if missionpack is installed or not. It is simply only compiled for TA not base game. So you only have to remove the missionpack defines (but don't forget to do this also in cg_local.h etc.).

**Comment by coltongit** [comment]
I could do that, but I'd have to experiment with it a little bit, due
to some of the sounds in missionpack that I want to use for baseq3
that don't exist in baseq3. Like prepare_team.wav for example.

**Comment by coltongit** [comment]
You also forgot cg_main.c @KuehnhammerTobias, but I managed to get everything all taken care of, but it's all default right now, if only I can figure out how to make a cvar & have the game options menu take care of those options...

**Comment by KuehnhammerTobias** [comment]
1. I didn't forget cg_main.c, this is what **etc.** stands for (at least in german).
2. You can use existing (cg) cvars as a reference.
3. This is a **closed non-issue** concerning mint-arena, move it to your issue tracker at coltongit/3wctf ?

**Comment by coltongit** [comment]
I'm also planning to use some of this for mint-arena as well, so an issue was opened here. And at last check, it's still open, & I plan to keep it open until I figure out if @zturtleman wants to do this or not in Spearmint. I think it could be useful for people who prefer them.

**Comment by coltongit** [comment]
Also, about 3wctf @KuehnhammerTobias, I happened to notice that there ARE green flames for the big q3dm7 flame near the RA. They exist in pak0.pk3 as g_flameX.tga (or are they jpg?).

**Comment by KuehnhammerTobias** [comment]
We know that there are green flames, but I don't know what you want to say to us when talking about the green flames...

**Comment by coltongit** [comment]
It means that it's possible to not have to include custom green flames when we make a version of q3dm7 designed for the 3-way CTF mod.

**Comment by zturtleman** [comment]
"I have audio problems (that aren't actually problems), and I have ideas about making Team Arena sounds be used in Q3A if they are present, and I found some images in pak0.pk3!"

Thank god we have an issue tracker so we conveniently track all of the multifaceted sides of this issue. But seriously, no I don't want to add these things. It's better done in mods. Trust me, you don't want all my ideas in mint-arena either.
