### ISSUE TITLE
Compatibility with ioquake3 protocol

### ISSUE THREAD

**Issue by 18woldemar** [zturtleman/spearmint#283]
Please, make the version compatible with ioquake3 servers. I like spearmint, but I want to play with other players on ioquake3 servers, it's more popular. Sorry for my bad English.

**Comment by zturtleman** [comment]
No, that's not going to happen because too many things are incompatible. Maybe my [widescreen HUD mod for ioquake3](https://clover.moe/flexible-hud-for-ioq3/) would be useful.
