### ISSUE TITLE
Support for ARM processors

### ISSUE THREAD

**Issue by apoklyps3** [zturtleman/spearmint#284]
I'm running armbian (ubuntu 18) on a device that has AMLogic S912 processor and I was wondering if there is any way to get spearmint up and running on it as a dedicated server.
Did so with ioquake, wich I read spearmint is based on so I was wondering if spearming can too. 
thanks in advance

**Comment by zturtleman** [comment]
Spearmint has the same build system as ioquake3 so Spearmint should build on ARM too.

**Comment by apoklyps3** [comment]
but I'll have to build that version myself from the source, correct?

**Comment by zturtleman** [comment]
Yeah. I think you should be able to compile and run it using the following:
```
sudo apt-get install make gcc git
git clone https://github.com/zturtleman/spearmint.git spearmint
cd spearmint
make BUILD_CLIENT=0 ARCH=armv7l
./build/release-linux-armv7l/spearmint-server_armv7l +map q3dm1
```
