### ISSUE TITLE
OpenGL2: cg_fadeExplosions 1 doesn't work correctly with r_dlightMode > 0

### ISSUE THREAD

**Issue by KuehnhammerTobias** [zturtleman/spearmint#294]
The option to fade out explosion lights instead of shrinking them (set cg_fadeExplosions cvar to 1), doesn't fade out the lights anymore. Instead the lights are vanishing abruptly. No shrinking, no fading. Fading the lights worked once though. Shrinking the lights (old behaviour) still works correctly.

**Comment by zturtleman** [comment]
Hmm... it works with Spearmint 1.0.1 with default settings using opengl1 and opengl2 renderers on GNU/Linux with Intel graphics. Maybe some other cvar is affecting it?

**Comment by KuehnhammerTobias** [comment]
Ah, yes, you are right, the issue only happens when cvar r_dlightMode is > 0. Feel free to close, or modify this issue ticket if you want. Sorry that I didn't test it with different cvar settings.

**Comment by zturtleman** [comment]
No problem. r_dlightMode 1 causes the issue for me as well.

**Comment by zturtleman** [comment]
Fixed in https://github.com/zturtleman/spearmint/commit/d5df159c3e770b10f490494ed04a2b8080caa8e0.
