### ISSUE TITLE
Support for Conjunction mod.

### ISSUE THREAD

**Issue by razvanab** [zturtleman/spearmint#317]
Can you please add support for conjunction mod please ?
https://www.moddb.com/mods/the-dark-conjunction/downloads/the-conjunction-10

If you need the src for the mod you can find it here:
https://filebin.net/hcdoa6rlzhbftwtl

Thank you.

**Comment by zturtleman** [comment]
I don't believe porting the source code can legally be done. I'm also not really accepting mod/game port requests.

The Dark Conjunction (and most Quake 3 mods) are available under the Quake 3 SDK EULA license which is incompatible with the full Quake 3 engine source code release, under the GNU General Public License (version 2 or later), that Spearmint is based on. So rebasing the code on Spearmint's Quake 3 mod code (mint-arena) is not possible.

**Comment by razvanab** [comment]
OK, thank you.
