### ISSUE TITLE
Request: can you add the support to quake 3 cinematic texture

### ISSUE THREAD

**Issue by luca2125** [zturtleman/spearmint#325]
Hi,

I ask if is possible add the support for quake 3 cinamatic mod:

https://www.moddb.com/mods/cinematic-mod-8k-and-16k-resolution-textures

actually work only on quake3e.

Thanks !

**Comment by KuehnhammerTobias** [comment]
Nice that you give Spearmint a try, but can you please give more information why this mod won't work for you, error message, etc.
It would help us to help you if we have more information.
Thanks.

**Comment by luca2125** [comment]
Yes:

This this command like work:

quake3e.x64.exe  +set fs_game cpmaV_CiNEmatic +set r_customHeight 1080 +set r_customWidth 1920 +set r_mode -1 +set com_hunkMegs 756

but if I run this not work:

spearmint_x86_64.exe  +set fs_game cpmaV_CiNEmatic +set r_customHeight 1080 +set r_customWidth 1920 +set r_mode -1 +set com_hunkMegs 756

![error](https://user-images.githubusercontent.com/55355625/124667379-9c6d8b80-deaf-11eb-9bf6-26967ea532e0.png)

//
Spearmint 1.0.2 win_mingw64-x86_64 Nov  3 2019
SSE instruction set enabled
----- FS_Startup -----
Using 'baseq3' as default game as specified in C:\Users\MarcoPanza\Downloads\Quake 3 Arena\spearmint-gamelist.txt.
Current search path:
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\settings\cpmaV_CiNEmatic\
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\cpmaV_CiNEmatic\
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\settings\fonts
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\fonts

----------------------
0 files in pk3 files

if I set 'CiNEmaticV11062' in this command line I get:

Spearmint 1.0.2 win_mingw64-x86_64 Nov  3 2019
SSE instruction set enabled
----- FS_Startup -----
Using 'baseq3' as default game as specified in C:\Users\MarcoPanza\Downloads\Quake 3 Arena\spearmint-gamelist.txt.
Current search path:
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\settings\CiNEmaticV11062\
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak999.pk3 (135 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak888.pk3 (74 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak777.pk3 (271 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak666.pk3 (56 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak555.pk3 (490 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak333.pk3 (440 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak222.pk3 (34 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak111.pk3 (20 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\settings\fonts
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\fonts

----------------------
1520 files in pk3 files

with the some error message

//

apart this cinematic MOD have 16k texture that is supported by  quake3e but I don't sure if is supported by spearmint or by ioquake.

I can provide more information if need.

**Comment by zturtleman** [comment]
Spearmint treats each fs_game as a standalone game. Add a mint-game.settings file to specify it's a Quake 3 mod.

Create CiNEmaticV11062\mint-game.settings with
```c
defaultSound "sound/feedback/hit.wav"
addLoadingScreen menuback ( 0 0 0 ) 1.333333

// This is a quake 3 mod, so add baseq3 to search path.
addGameDir baseq3
```

**Comment by luca2125** [comment]
done, Now I get this error:

![errore2](https://user-images.githubusercontent.com/55355625/124711131-fa28c480-defd-11eb-8ea9-a6221c2e2345.png)

probably there is a memory limit.

**Comment by KuehnhammerTobias** [comment]
You can try to set your com_zoneMegs setting to a higher value (e.g.: 128 or 256, 512). Though, I'm in doubt this will really help much.
It's just my own opinion but I never saw a good software that improvers texture quality by just hitting a few buttons, and the AI will do the rest. Probably that is why so many resources are used/wasted within this mod.
What helped me in the past was to convert textures to DDS format (which reduces VRAM usage). Of course this means you need to get in contact with the author and ask him for a DDS texture version of his mod.
The problem is that only Spearmint and ioquake3 supports DDS files, Quake3e does not as far as I know. Additionally using DDS format even improves level loading times really a lot.

**Comment by luca2125** [comment]
I have asked this question to CiNEmatic mod developer and I wating for response. In the meantime. I ask if you think in the future to add Visual Studio project files (I have not too much familiarity with linux). Apart this I have asked to CiNEmatic mod developer why he don't re-worked the enemy and he ask me that the number of polygons is limitated on engine but it is not clear if is possible reduce this limit.

**Comment by KuehnhammerTobias** [comment]
> I ask if you think in the future to add Visual Studio project files
I'm not the developer of Spearmint (which is zturtleman), so I can't say anything about the future of Spearmint. Currently Spearmint isn't in active development, moreover the Visual Studio project files were deleted from Spearmint, so it's unlikely Spearmint will come with Visual Studio project files in the future I think.
If you need help compiling Spearmint than please let me know, there are 'better' was to compile Spearmint and/or ioquake3 than using MSVC, imo.

> the number of polygons is limitated on engine but it is not clear if is possible reduce this limit
Yes the number is limited (for good reason there is always a limit). The question is how to push these limits to a reasonable amount. Most game developers want their game to still remain playable (even on weaker systems), just convert everything into High Quality (whatever that means) often make games useless.

**Comment by zturtleman** [comment]
> done, Now I get this error:
> 
> ![errore2](https://user-images.githubusercontent.com/55355625/124711131-fa28c480-defd-11eb-8ea9-a6221c2e2345.png)
> 
> probably there is a memory limit. With quake3e and the some command line work.

Quake3e automatically increases the zone memory size as needed. For official Quake 3, ioquake3, and Spearmint you need to pass `+set com_zoneMegs 512` on the command line or whatever size works.

**Comment by luca2125** [comment]
thank you !!!

with this line work:

spearmint_x86_64.exe  +set fs_game CiNEmaticV11062 +set r_customHeight 1080 +set r_customWidth 1920 +set r_mode -1 +set com_hunkMegs 756 +set com_zoneMegs 512

**Comment by zturtleman** [comment]
Okay, cool. You can reopen this issue if there is another issue with the mod.
