### ISSUE TITLE
Team Arena won't play in 1080p

### ISSUE THREAD

**Issue by Sixteen60** [zturtleman/spearmint#333]
I put the pak0.pk3 file of Quake 3 Team Arena into Spearmint, but when I tried to load Team Arena I get an error that says "missing default PK3 files." And I click "OK" and it starts up Team Arena. However when I do, it appears in windowed and I can't play in 1080p when I could with the base game in Spearmint. What am I supposed to do?

**Comment by zturtleman** [comment]
To fix the "missing default PK3 files" you can download the official Team Arena patch pak[1-3].pk3 at [ioquake3 patch data download](https://ioquake3.org/extras/patch-data/). Open the zip and extract the missionpack pk3s into the to missionpack directory in the Spearmint download.

At present, to use 1080p in Team Arena you need to set some console variables. Open Team Arena and then open the console using ~ or shift+escape, use ctrl+v to paste
```
r_fullscreen 1; r_mode -1; r_customwidth 1920; r_customheight 1080; vid_restart
```
and press enter.

The Spearmint 1.1 release (no release date) will have the [same resolution list in Team Arena](https://github.com/zturtleman/mint-arena/commit/278b7de324251f7b0542c75e6929e0ed8e6176de) (missionpack) as in Quake 3 (baseq3). It will allow the native monitor resolution to be selected in the Team Arena options→setup→system menu.
