### ISSUE TITLE
Spearmint and OBS

### ISSUE THREAD

**Issue by ghost** [zturtleman/spearmint#342]
I play Quake 3 on this amazing engine, but here's the problem, when trying to record a broadcast in OBS, she doesn't want to display the game. Is there any patch or any settings that you can stream this game?

**Comment by zturtleman** [comment]
I'm not familiar with using OBS. I tried OBS on Linux (X11) and it was able to record the Spearmint window. OBS not capturing OpenGL windows created using the SDL 2 library may be a question for OBS.
