### ISSUE TITLE
OpenGL2: minor fix for Splitscreen view.

### ISSUE THREAD

**Issue by KuehnhammerTobias** [zturtleman/spearmint#343]
I think a fix was made for OpenGL1, but was not merged into the second renderer?

The description of the fix for GL1:
> Fix marks on brushes in second player's view. Fixed bmodel entitynum when not drawing first scene, which happens for additional players in splitscreen.

The commit that fixed the issue: https://github.com/zturtleman/spearmint/commit/52fe5b71183161673083bb156153e3b4ce61312f

As far as I can see, the issue is still the case when using OpenGL2, that's why I think it would be cool if this would be fixed for GL2 as well.

**Comment by zturtleman** [comment]
Yeah, this change is still relevant for the opengl2 renderer. Thanks.

Fixed for 1.1.0 in https://github.com/zturtleman/spearmint/commit/a702e741e2fdcf593ad9d0734d2b9d94b5e75a22, fixed for 1.0.4 in https://github.com/zturtleman/spearmint/commit/e0cc1980761601b7216d774b0a298d9f67769d01.
